# Generated by Django 5.0.6 on 2024-07-12 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_categories_colors_sizes_subcategories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Colors',
            new_name='Color',
        ),
        migrations.RenameModel(
            old_name='Sizes',
            new_name='Size',
        ),
        migrations.RenameModel(
            old_name='Subcategories',
            new_name='Subcategory',
        ),
    ]
