# Generated by Django 5.0.6 on 2024-07-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_categories_category_rename_colors_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
