# Generated by Django 5.0.6 on 2024-07-13 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_productclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productclass',
            old_name='category',
            new_name='subcategory',
        ),
    ]
