# Generated by Django 5.0.6 on 2024-07-13 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_paymentmethods_order_gift_wrap_order_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='app.order')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method', to='app.paymentmethods')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_date', models.DateTimeField()),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(max_length=8)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_shipment', to='app.order')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_region', to='app.region')),
            ],
        ),
    ]
