# Generated by Django 5.0.6 on 2024-07-13 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_region_payment_shipment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentMethods',
            new_name='PaymentMethod',
        ),
    ]
