# Generated by Django 5.0.6 on 2024-07-13 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_paymentmethods_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_order', to='app.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product', to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload1', models.ImageField(upload_to='app/product_images')),
                ('upload2', models.ImageField(upload_to='app/product_images')),
                ('upload3', models.ImageField(upload_to='app/product_images')),
                ('upload4', models.ImageField(upload_to='app/product_images')),
                ('upload5', models.ImageField(upload_to='app/product_images')),
                ('upload6', models.ImageField(upload_to='app/product_images')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_photos', to='app.product')),
            ],
        ),
    ]
