# Generated by Django 5.0.6 on 2024-07-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_product_color_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='upload1',
            field=models.ImageField(null=True, upload_to='app/product_images'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='upload2',
            field=models.ImageField(null=True, upload_to='app/product_images'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='upload3',
            field=models.ImageField(null=True, upload_to='app/product_images'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='upload4',
            field=models.ImageField(null=True, upload_to='app/product_images'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='upload5',
            field=models.ImageField(null=True, upload_to='app/product_images'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='upload6',
            field=models.ImageField(null=True, upload_to='app/product_images'),
        ),
    ]
