# Generated by Django 5.0.6 on 2024-07-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_productgallery_upload1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='upload1',
            field=models.ImageField(blank=True, null=True, upload_to='app/product_images'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='upload2',
            field=models.ImageField(blank=True, null=True, upload_to='app/product_images'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='upload3',
            field=models.ImageField(blank=True, null=True, upload_to='app/product_images'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='upload4',
            field=models.ImageField(blank=True, null=True, upload_to='app/product_images'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='upload5',
            field=models.ImageField(blank=True, null=True, upload_to='app/product_images'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='upload6',
            field=models.ImageField(blank=True, null=True, upload_to='app/product_images'),
        ),
    ]
