# Generated by Django 5.0.6 on 2024-07-23 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_productgallery_upload1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductGallery',
        ),
    ]
