# Generated by Django 5.0.6 on 2024-07-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/products/'),
        ),
    ]
