# Generated by Django 5.0.6 on 2024-07-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_product_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='specifications',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/items/'),
        ),
    ]
