# Generated by Django 5.0.6 on 2024-08-20 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
